
CREATE DATABASE BDACLINICA;
USE BDACLINICA;



CREATE TABLE TB_FORMU_PACIENTE (
  COD_FORMULARIO int(20) NOT NULL,
  COD_PACIENTE int(20) DEFAULT NULL,
  CEPILLA int(20) DEFAULT NULL,
  HILO varchar(10) DEFAULT NULL,
  LENGUA varchar(10) DEFAULT NULL,
  SANGRA varchar(10) DEFAULT NULL,
  MOTIVO varchar(100) DEFAULT NULL,
  MOLESTIA varchar(10) DEFAULT NULL,
  ES varchar(10) DEFAULT NULL,
  DUELE varchar(10) DEFAULT NULL,
  INFLAMACION varchar(10) DEFAULT NULL,
  COLOR varchar(10) DEFAULT NULL,
  ALIENTO varchar(10) DEFAULT NULL,
  ULTIMA_VEZ int(11) DEFAULT NULL,
  EMBARAZADA varchar(10) DEFAULT NULL,
  MEDICAMENTO varchar(10) DEFAULT NULL,
  ANESESIA varchar(10) DEFAULT NULL,
  PIEZA varchar(10) DEFAULT NULL,
  HEMORRAGIA varchar(10) DEFAULT NULL,
  ENFERMEDAD varchar(10) DEFAULT NULL,
  ENFERMEDAD2 varchar(10) DEFAULT NULL,
  HOSPITALIZADO varchar(10) DEFAULT NULL,
  PORQUE varchar(100) DEFAULT NULL,
  PRIMARY KEY (COD_FORMULARIO),
  KEY COD_PACIENTE (COD_PACIENTE),
  CONSTRAINT TB_FORMU_PACIENTE_ibfk_1 FOREIGN KEY (COD_PACIENTE) REFERENCES TB_PACIENTES (COD_PACIENTE)
);




CREATE TABLE TB_HISTORIAL (
  COD_HISTORIAL int(20) NOT NULL,
  COD_PACIENTE int(20) DEFAULT NULL,
  FECHA_HISTORIAL timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PIEZA float(20,5) DEFAULT NULL,
  CONDUCTO varchar(1000) DEFAULT NULL,
  CONDUCTOMETRIA varchar(1000) DEFAULT NULL,
  BASE varchar(100) DEFAULT NULL,
  OTB varchar(100) DEFAULT NULL,
  OBSERVACIONES varchar(1000) DEFAULT NULL,
  USUARIO varchar(20) DEFAULT NULL,
  ESTADO varchar(20) DEFAULT NULL,
  PRIMARY KEY (COD_HISTORIAL),
  KEY COD_PACIENTE (COD_PACIENTE),
  CONSTRAINT TB_HISTORIAL_ibfk_1 FOREIGN KEY (COD_PACIENTE) REFERENCES TB_PACIENTES (COD_PACIENTE)
);




CREATE TABLE TB_IMAGENES (
  ID_IMAGEN int(20) NOT NULL,
COD_PACIENTE int(20) DEFAULT NULL,
  NOMBRE varchar(100) DEFAULT NULL,
  OBSERVACION varchar(100) DEFAULT NULL,
  IMAGEN varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID_IMAGEN),
  KEY COD_PACIENTE (COD_PACIENTE),
  CONSTRAINT TB_IMAGENES_ibfk_1 FOREIGN KEY (COD_PACIENTE) REFERENCES TB_PACIENTES (COD_PACIENTE)
); 



CREATE TABLE TB_PACIENTES (
  COD_PACIENTE int(11) NOT NULL DEFAULT '0',
  APELLIDOS varchar(50) DEFAULT NULL,
  APELLIDOS2 varchar(50) DEFAULT NULL,
  NOMBRES varchar(50) DEFAULT NULL,
  NOMBRES2 varchar(50) DEFAULT NULL,
  FECHA_NACIMIENTO varchar(50) DEFAULT NULL,
  DIRECCION varchar(50) DEFAULT NULL,
  TELEFONO_RECIDENCIAL int(11) DEFAULT NULL,
  CELULAR1 int(11) DEFAULT NULL,
  CELULAR2 int(11) DEFAULT NULL,
  REFERIDO varchar(50) DEFAULT NULL,
  OCUPACION varchar(50) DEFAULT NULL,
  DPI varchar(50) DEFAULT NULL,
  ESTADO varchar(20) DEFAULT NULL,
  PRIMARY KEY (COD_PACIENTE)
);


CREATE TABLE TB_PAGOS (
  ID_PAGO int(11) NOT NULL DEFAULT '0',
  COD_PACIENTE int(20) DEFAULT NULL,
  COD_PRESUPUESTO int(11) NOT NULL,
  FECHA_PAGO date DEFAULT NULL,
  PAGO float(8,2) DEFAULT NULL,
  SALDO float(8,2) DEFAULT NULL,
  USUARIO varchar(100) DEFAULT NULL,
  NO_RECIBO int(11) DEFAULT NULL,
  ESTADO varchar(20) DEFAULT NULL,
  PRIMARY KEY (ID_PAGO),
  KEY COD_PACIENTE (COD_PACIENTE),
  KEY COD_PRESUPUESTO (COD_PRESUPUESTO),
  CONSTRAINT TB_PAGOS_ibfk_1 FOREIGN KEY (COD_PACIENTE) REFERENCES TB_PACIENTES (COD_PACIENTE),
  CONSTRAINT TB_PAGOS_ibfk_2 FOREIGN KEY (COD_PRESUPUESTO) REFERENCES TB_PRESUPUESTO (COD_PRESUPUESTO)
);





CREATE TABLE TB_PRESUPUESTO (
  COD_PRESUPUESTO int(20) NOT NULL,
  COD_PACIENTE int(20) DEFAULT NULL,
  PIEZA varchar(20) DEFAULT NULL,
  TRATAMIENTO varchar(100) DEFAULT NULL,
  PRECIO float(8,2) DEFAULT NULL,
  USUARIO varchar(20) DEFAULT NULL,
  FECHA varchar(20) DEFAULT NULL,
  ESTADO varchar(20) DEFAULT NULL,
  PRIMARY KEY (COD_PRESUPUESTO),
  KEY COD_PACIENTE (COD_PACIENTE),
  CONSTRAINT TB_PRESUPUESTO_ibfk_1 FOREIGN KEY (COD_PACIENTE) REFERENCES TB_PACIENTES (COD_PACIENTE)
);




CREATE TABLE TB_USUARIOS (
  COD_USUARIO int(11) NOT NULL,
  APELLIDO_USUARIO varchar(30) DEFAULT NULL,
  NOMBRE_USUARIO varchar(30) DEFAULT NULL,
  PAIS varchar(50) DEFAULT NULL,
  PERFIL varchar(30) DEFAULT NULL,
  CORREO varchar(50) DEFAULT NULL,
  CLAVE_USUARIO varchar(20) DEFAULT NULL,
  FECHA_CREACION varchar(20) DEFAULT NULL,
  ESTADO varchar(10) DEFAULT NULL,
  PRIMARY KEY (COD_USUARIO)
); 





INSERT INTO TB_USUARIOS VALUES (1,'HERRERA','OCTAVIO','HUEHUE','ADMIN','OCTAVIO@GMAIL.COM','ABC.123','2018-09-24 21:55:34','ACTIVO');

INSERT INTO TB_USUARIOS VALUES (2,'GOMEZ','LUIS','HUEHUE','ADMIN','OCTAVIO@GMAIL.COM','ABC.123','2018-09-24 21:55:34','ACTIVO');

SELECT * FROM TB_USUARIOS;


